import LandingLayout from "@components/layouts/LandingLayout";
import type { NextPage } from "next";
import Head from "next/head";

const HiringPage: NextPage = () => {
  return(
    <div>
      <Head>
        <title>Britjobs | Hiring?</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <LandingLayout>
        <div className="mx-auto max-w-screen-2xl">
          <h1 className="text-5xl">Hiring?</h1>
          <p>Post a job</p>
        </div>
      </LandingLayout>
    </div>
  )
}

export default HiringPage
